---
- hosts: all
  become: true
  tasks:
    - name: Verificar se os pacotes apt precisam ser atualizados
      become: yes
      command: apt-get -s upgrade
      register: apt_upgrade_check
      changed_when: false
      ignore_errors: true

    - name: Atualizar pacotes apt
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
      when: apt_upgrade_check.rc == 0 and "Pacotes a serem atualizados:" in apt_upgrade_check.stdout

    - name: Verificar se o Docker Compose está instalado
      become: yes
      shell: docker-compose --version
      register: docker_compose_check
      ignore_errors: true

    - name: Instalar Docker Compose se não estiver instalado
      become: yes
      shell: curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      when: docker_compose_check.rc != 0

    - name: Saia se o Docker Compose estiver instalado
      become: yes
      run_once: yes
      meta: end_play
      when: docker_compose_check.rc == 0



