---
- hosts: all
  become: yes
  tasks:
    - name: Verificar se o Docker está atualizado
      shell: docker --version | awk '{print $3}'
      register: docker_version_output

    - name: Mostrar a versão atual do Docker
      debug:
        var: docker_version_output.stdout

    - name: Atualizar o Docker se necessário
      apt:
        name: docker-ce
        state: latest
      when: "docker_version_output.stdout | version_compare('20.10', '>=')"

