---
- hosts: all
  become: yes
  tasks:
    - name: Verificar se o Docker está instalado
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Instalar o Docker se não estiver instalado
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker
      when: docker_installed.rc != 0

    - name: Reiniciar o serviço Docker
      service:
        name: docker
        state: restarted
      when: docker_installed.rc != 0

    - name: Instalar o Docker Compose
      shell: curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose




