---
- hosts: all
  become: yes
  tasks:
    - name: Cria a rede externa
      shell: >
        docker network ls | grep -q 'node_js_default' || docker network create
        --driver=overlay node_js_default
        
    - name: Para a stack
      shell: docker stack down node_js
      
    - name: Remove a imagem antiga
      shell: docker image rm -f dockerimages.ddns.net/fjapi/nodex64:latest
      
    - name: Baixa a nova imagem
      shell: docker pull dockerimages.ddns.net/fjapi/nodex64:latest
      
    - name: Redeploy da stack
      shell: docker stack deploy -c docker-compose.yml node_js
      
    - name: Descriptografa o token do Telegram
      shell: ansible-vault decrypt secret.yaml
      register: decrypted_secret
      
    - name: Descriptografa o token do Telegram
  shell: ansible-vault decrypt secret.yaml
  register: decrypted_secret
  
- name: Envia mensagem para o Telegram
  telegram:
    api_method: sendMessage
    api_args:
      text: Imagem submetida com sucesso
      chat_id: 6632854362
      token: "{{ decrypted_secret.stdout_lines[0] }}"





