---
- hosts: all
  become: true
  become_user: root

  tasks:
    - name: Limpar bloqueios
      shell: rm -f /var/lib/apt/lists/lock
      ignore_errors: true

    - name: Atualizar pacotes apt
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

