- hosts: all
  become: true
  become_user: root

  tasks:
    - name: Remover arquivo de bloqueio do apt
      become: yes
      file:
        path: /var/lib/apt/lists/lock
        state: absent

    - name: Atualizar pacotes apt
      become: yes
      apt:
        update_cache: yes
        upgrade: yes


