- hosts: all
  become: true
  tasks:
    - name: Verificar se os pacotes apt precisam ser atualizados
      become: yes
      shell: apt-get -s upgrade | grep -q 'Pacotes a serem atualizados:'
      register: apt_update_needed
      changed_when: false

    - name: Atualizar pacotes apt
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
      when: apt_update_needed.stdout == "true"


