---
- hosts: all
  tasks:
    - name: Limpar bloqueios apt
      shell: rm -f /var/lib/apt/lists/lock
      ignore_errors: true

    - name: Atualizar pacotes apt
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

