---
- hosts: all
  become: true
  become_user: root

  tasks:
    - name: Remover arquivo de bloqueio do apt
      become: yes
      file:
        path: /var/lib/apt/list/lock
        state: absent
        ignore_errors: yes

    - name: Atualizar pacotes apt
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
        force_apt_get: yes

